#!/bin/bash

# Reset
Color_Off=''

# Regular Colors
Red=''
Green=''
Yellow=''
Cyan=''
Magenta=''
Dim='' # White

# Bold
Bold_White=''
Bold_Green=''

if [[ -t 1 ]]; then
    # Reset
    Color_Off='\033[0m' # Text Reset

    # Regular Colors
    Red='\033[0;31m'   # Red
    Green='\033[0;32m' # Green
    Yellow='\033[1;33m' # Yellow
    Cyan='\033[0;36m'
    Magenta='\033[1;35m'
    Dim='\033[0;2m'    # White

    # Bold
    Bold_Green='\033[1;32m' # Bold Green
    Bold_White='\033[1m'    # Bold White
fi

error() {
    echo -e "${Red}error${Color_Off}:" "$@" >&2
    exit 1
}

info() {
    echo -e "${Dim}$@ ${Color_Off}"
}

info_bold() {
    echo -e "${Bold_White}$@ ${Color_Off}"
}

success() {
    echo -e "${Green}$@ ${Color_Off}"
}

bold_success() {
    echo -e "${Bold_Green}$@ ${Color_Off}"
}

intro() {
    echo -e "${Yellow}$@ ${Color_Off}"
}


bold_success "                                                  "
bold_success "                                                  " 
bold_success "          █▄▀ █░█ █▄░█ ▄▀█ █░░   █▀ █ █▄░█ █▀▀ █░█"
bold_success "          █░█ █▄█ █░▀█ █▀█ █▄▄   ▄█ █ █░▀█ █▄█ █▀█"
bold_success "                                                  "
bold_success "                                                  "

intro "          Hey there, I'm Kunal a 2nd-year Computer Science and Engineering Student." 
intro "          I love making new stuff using code, and I am fascinated by open-source"
intro "          and love to contribute."

info  "                                                                                          "
info  "          I'm currently working on a small project called ${Bold_White}doingto${Color_Off}" 
info  "          See: ${Cyan}https://doingto.live/${Color_Off}"

info  "                                                                                          "
info  "          I write about tech and stuff sometime, see my ${Bold_White}Blog${Color_Off}: ${Cyan}https://blog.kunalsin9h.dev/${Color_Off}"
info  "                                                                                          "

info      "          ${Magenta}Connect${Color_Off}"
info_bold "          Email: kunal@kunalsin9h.dev"
info_bold "          GitHub: ${Cyan}https://github.com/KunalSin9h${Color_Off}"
info_bold "          Tiwtter: ${Cyan}https://twitter.com/KunalSin9h${Color_Off}"
info ""
